### ISSUE TITLE
cart license in distribution.  

### ISSUE THREAD

**Issue by jpfielding** [trulia/trulia-java-rets-client#7]
when going back to review the original cart license after you'ld contacted me i realized i should have had the original license with the code as it was a licensing requirement from cart

http://cart.sourceforge.net/documentation/license/

**Comment by chadcurry** [comment]
@vangulo-trulia -> @jpfielding - thanks for this note. I was actually just reaching out w/r/t this issue of license. Since this is a derivative work, the license provided by @jpfielding should be part of the distribution. Please add the license ASAP. Thank you.

**Comment by vangulo-trulia** [comment]
just wanted to confirm the change and say thank you for the heads up
